=== schtibe/Projektarbeit-2-7302/ressources/data/worldschema.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
	<xs:element name="world" type="world"/>
		
	<!-- Definition of type world -->
	
	<xs:complexType name="world">
		<xs:sequence>
			<xs:element name="road" maxOccurs="unbounded" minOccurs="1" type="road" />
			<xs:element name="junction" maxOccurs="unbounded" minOccurs="1" type="junction"/>
		</xs:sequence>
		<xs:attribute name="scale" type="xs:float"></xs:attribute>
	</xs:complexType>
	
	<!-- Definition of type road -->
	
	<xs:complexType name="road">
		<xs:sequence>
			<xs:element name="leftlanes" maxOccurs="1" minOccurs="1" type="lane_collection"/>
			<xs:element name="rightlanes" maxOccurs="1" minOccurs="1" type="lane_collection"/>
			<xs:element name="roadsegments" maxOccurs="1" minOccurs="1" type="segment_collection"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="startX" type="xs:integer" use="required" />
		<xs:attribute name="startY" type="xs:integer" use="required" />
	</xs:complexType>
	
	<!-- Definition of type junction -->
	
	<xs:complexType name="junction">
		<xs:sequence>
			<xs:element name="roads" minOccurs="1" maxOccurs="1" type="road_collection"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="id" type="xs:integer" use="required" />
	</xs:complexType>
	
	<!-- Definition of type lane_collection -->
	
	<xs:complexType name="lane_collection">
		<xs:sequence>
			<xs:element name="lane" type="lane" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definition of type lane -->
	
	<xs:complexType name="lane">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="waypoints" type="waypoint_collection" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
		<xs:attribute name="width" type="xs:integer" use="required"/>
	</xs:complexType>
	
	<!-- Definition of type segment_collection -->
	
	<xs:complexType name="segment_collection">
		<xs:sequence>
			<xs:element name="roadsegment" type="segment" minOccurs="1" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definition of type segment -->
	
	<xs:complexType name="segment">
		<xs:attribute name="order" type="xs:integer" use="required"/>
		<xs:attribute name="startX" type="xs:integer" use="required"/>
		<xs:attribute name="startY" type="xs:integer" use="required"/>
		<xs:attribute name="endX" type="xs:integer" use="required"/>
		<xs:attribute name="endY" type="xs:integer" use="required"/>
	</xs:complexType>
	
	<!-- Definition of type waypoint_collection -->
	
	<xs:complexType name="waypoint_collection">
		<xs:sequence>
			<xs:element name="SpeedWaypoint" type="SpeedWaypoint" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definition of type SpeedWaypoint -->
	
	<xs:complexType name="SpeedWaypoint">
		<!--<xs:attribute name="direction" type="direction" use="required"/>-->
		<xs:attribute name="id" type="xs:integer" use="required"/>
		<xs:attribute name="value" type="xs:integer" use="required"/>
		<xs:attribute name="position" type="float" use="required"/>
		<xs:attribute name="direction" type="xs:string" use="required"/> <!-- should probably something else that string to restrict to right, left, both -->
	</xs:complexType>
	
	<!-- Definition of simple type direction -->
	
	<!--<xs:simpleType name="direction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left"/>
			<xs:enumeration value="right"/>
			<xs:enumeration value="both"/>
		</xs:restriction>
	</xs:simpleType>
	-->
	
	<!-- Defintion of simple type float -->
	
	<xs:simpleType name="float">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Definition of type road_collection -->
	
	<xs:complexType name="road_collection">
		<xs:sequence>
			<xs:element name="road" type="junction_road" minOccurs="2" maxOccurs="4"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definition of type junction_road -->
	
	<xs:complexType name="junction_road">
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== schtibe/Projektarbeit-2-7302/ressources/data/drivermodel.xml
<?xml version="1.0" encoding="utf-8" ?>
<world xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:ressources/data/worldschema.xsd" scale="1.0">
	<!-- first road is single lane, used to simulate the starting procedure of a vehicle -->
	<road id="1" startX="20" startY="0">
		<leftlanes>

		</leftlanes>
		<rightlanes>
			<lane id="1" width="1" >
				<waypoints>
					<SpeedWaypoint id="1" value="30" position="0.0" direction="right"/>
				</waypoints>
			</lane>
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="380" endY="0" />
			<roadsegment order="2" startX="400" startY="20" endX="400" endY="460"/>
		</roadsegments>
	</road>
	<!-- second road is double line, model allows that but how is the builder reacting to this -->
	<road id="2" startX="400" startY="480">
		<leftlanes>
			<lane id="1" width="1" >
				<waypoints>
					<SpeedWaypoint id="1" value="50" position="0.1" direction="right"/>
				</waypoints>
			</lane>
		</leftlanes>
		<rightlanes>
			<lane id="1" width="1" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="-380" endY="0" />
		</roadsegments>
	</road>
	<road id="3" startX="0" startY="460">
		<leftlanes>
			<lane id="1" width="1" />
		</leftlanes>
		<rightlanes>
			<lane id="1" width="1" >
				<waypoints>
					<SpeedWaypoint id="1" value="80" position="0.1" direction="right"/>
				</waypoints>
			</lane>
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="-440"/>
		</roadsegments>
	</road>
	<junction id="1" type="CrossRoad">
		<roads>
			<road id="1" />
			<road id="2" />
		</roads>
	</junction>
	<junction id="2" type="CrossRoad">
		<roads>
			<road id="2" />
			<road id="3" />
		</roads>
	</junction>
	<junction id="3" type="CrossRoad">
		<roads>
			<road id="3" />
			<road id="1" />
		</roads>
	</junction>
</world>

=== schtibe/Projektarbeit-2-7302/ressources/data/world.xml
<?xml version="1.0" encoding="utf-8" ?>
<world xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="file:ressources/data/worldschema.xsd" scale="1.0">
<!--<world xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="file:worldschema.xsd" scale="1.0">
	<road id="1" startX="500" startY="500">
		<leftlanes>
			<lane id="1" width="20"/>
		</leftlanes>
		<rightlanes>
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="-300"/>
			<roadsegment order="2" startX="-100" startY="-400" endX="-400" endY="-400"/>
		</roadsegments>
	</road>
	<road id="2" startX="0" startY="200">
		<leftlanes>
			<lane id="1" width="20"/>   
		</leftlanes>
		<rightlanes>
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="300"/>
		</roadsegments>
	</road>
	<road id="3" startX="500" startY="700">
		<leftlanes>
			<lane id="1" width="20"/>
		</leftlanes>
		<rightlanes>
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="300" />
			<roadsegment order="2" startX="100" startY="400" endX="400" endY="400"/>
		</roadsegments>
	</road>
	<road id="4" startX="1000" startY="1000">
		<leftlanes>
			<lane id="1" width="20"/>
		</leftlanes>
		<rightlanes>
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="-300" />
			<roadsegment order="2" startX="-100" startY="-400" endX="-400" endY="-400"/>
		</roadsegments>
	</road>
	<junction type="CrossRoad" id="1">
		<roads>
			<road id="1" />
			<road id="2" />
		</roads>
	</junction>
	<junction type="CrossRoad" id="2">
		<roads>
			<road id="3" />
			<road id="4" />
		</roads>
	</junction>
	<junction type="CrossRoad" id="3">
		<roads>
			<road id="2" />
			<road id="4" />
			<road id="1" />
			<road id="3" />
		</roads>
	</junction>-->

	<road id="1" startX="500" startY="0">
		<leftlanes>
			<lane id="1" width="5"/>
		</leftlanes>
		<rightlanes>
			<lane id="1" width="5" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="-400" endY="0" /> 	
		</roadsegments>
	</road>
	<road id="2" startX="0" startY="100">
		<leftlanes>
			<lane id="1" width="5"/>
		</leftlanes>
		<rightlanes>
			<lane id="1" width="5" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="2" startX="0" startY="0" endX="0" endY="400" />
		</roadsegments>
	</road>
	<road id="3" startX="100" startY="600">
		<leftlanes>
			<lane id="1" width="5"/>
		</leftlanes>
		<rightlanes>
			<lane id="1" width="5" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="2" startX="0" startY="0" endX="400" endY="0" />
		</roadsegments>
	</road>	
	<road id="4" startX="600" startY="400" >
		<leftlanes>
			<lane id="1" width="5"/>
		</leftlanes>
		<rightlanes>
			<lane id="2" width="5" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="-300" />
		</roadsegments>
	</road>
	<road id="5" startX="700" startY="550" >
		<leftlanes>
			<lane id="1" width="5"/>
		</leftlanes>
		<rightlanes>
			<lane id="2" width="5" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="400" endY="-250" />
			<roadsegment order="2" startX="400" startY="-350" endX="0" endY="-500" />
		</roadsegments>
	</road>
	<road id="6" startX="100" startY="700" >
		<leftlanes>
			<lane id="1" width="5" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="5" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="150" endY="150"/>
			<roadsegment order="2" startX="250" startY="150" endX="400" endY="0"/>
		</roadsegments>
	</road>
	<junction type="CrossRoad" id="1">
		<roads>
			<road id="1" />
			<road id="2" />
		</roads>
	</junction>
	<junction type="CrossRoad" id="2">
		<roads>
			<road id="2" />
			<road id="3" />
			<road id="6" />
		</roads>
	</junction>
	<junction type="CrossRoad" id="3">
		<roads>
			<road id="3" />
			<road id="4" />
			<road id="5" />
			<road id="6" />
		</roads>
	</junction>
	<junction type="CrossRoad" id="4">
		<roads>
			<road id="4" />
			<road id="1" />
			<road id="5" />
		</roads>
	</junction>
</world>

=== schtibe/Projektarbeit-2-7302/ressources/oldworlds/bern.xml
<?xml version="1.0" encoding="utf-8" ?>
<world 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:../ressources/data/worldschema.xsd">
	<road id="1" startX="1325" startY="400" name="Brunngasse">
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="-200" /> 
			<roadsegment order="2" startX="-325" startY="-300" endX="-1000" endY="-300" />
			<roadsegment order="3" startX="-1200" startY="-200" endX="-1250" endY="0" />
		</roadsegments>
	</road> 
	<road id="2" startX="50" startY="450" name="Hotelgasse">
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="-50" endY="300" />
		</roadsegments>
	</road>
	<road id="3" startX="0" startY="800" name="Hotelgasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="400" />
		</roadsegments>
	</road>
	<road id="4" startX="0" startY="1250" name="Hotelgasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="200" />
		</roadsegments>
	</road>
	<road id="4" startX="125" startY="425" name="Rathausgasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="1150" endY="0" />
		</roadsegments>
	</road>
	<road id="5" startX="1375" startY="450" name="Rathausgasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="950" endY="0" />
		</roadsegments>
	</road>
	<road id="6" startX="2400" startY="400" name="Postgasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="1875" endY="-400" />
		</roadsegments>
	</road>
	<road id="7" startX="4325" startY="100" name="Postgasshalde" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="75" endY="150" />
		</roadsegments>
	</road>
	<road id="8" startX="4375" startY="275" name="Gerechtigkeitsgasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="-1900" endY="550" />
		</roadsegments>
	</road>
	<road id="9" startX="4450" startY="350" name="Junkerngasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="50" endY="100" />
			<roadsegment order="1" startX="-200" startY="300" endX="-2000" endY="800" />
		</roadsegments>
	</road>
	<road id="10" startX="2375" startY="500" name="Gässchen" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="50" endY="275" />
		</roadsegments>
	</road>
	<road id="11" startX="2375" startY="850" name="Kramgasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="-2300" endY="-75" />
		</roadsegments>
	</road>
	<road id="12" startX="2425" startY="900" name="Gässchen" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="0" endY="225" />
		</roadsegments>
	</road>
	<road id="13" startX="2400" startY="1150" name="Münstergasse" >
		<leftlanes>
			<lane id="1" width="25" />
		</leftlanes>
		<rightlanes>
			<lane id="2" width="25" />
		</rightlanes>
		<roadsegments>
			<roadsegment order="1" startX="0" startY="0" endX="-2350" endY="75" />
		</roadsegments>
	</road>
	<junction type="CrossRoad" id="1">
		<roads>
			<road id="1" />
			<road id="2" />
			<road id="4" />
		</roads>
	</junction>
	<junction type="CrossRoad" id="2">
		<roads>
			<road id="2" />
			<road id="3" />
			<road id="11" />
		</roads>
	</junction>
	<junction type="CrossRoad" id="3">
		<roads>
			<road id="1"/>
			<road id="5"/>
			<road id="4"/>
		</roads>
	</junction>
	<junction type="CrossRoad" id="4">
		<roads>
			<road id="5"/>
			<road id="6"/>
			<road id="10"/>
		</roads>
	</junction>
	<junction type="CrossRoad" id="5">
		<roads>
			<road id="7"/>
			<road id="8"/>
			<road id="9"/>
		</roads>
	</junction>
	<junction type="CrossRoad" id="6">
		<roads>
			<road id="6"/>
			<road id="7"/>
		</roads>
	</junction>
	<junction type="CrossRoad" id="7">
		<roads>
			<road id="8"/>
			<road id="10"/>
			<road id="11"/>
			<road id="12"/>
		</roads>
	</junction>
	<junction type="CrossRoad" id="8">
		<roads>
			<road id="9"/>
			<road id="12"/>
			<road id="13"/>
		</roads>
	</junction>
	<junction type="CrossRoad" id="9">
		<roads>
			<road id="3"/>
			<road id="13"/>
		</roads>
	</junction>
</world>
